# Generated by Django 6.0.2 on 2026-03-22 21:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0002_emailverification_remove_user_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='User',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pet',
            name='status',
            field=models.CharField(choices=[('dead', 'Dead'), ('unavailable', 'Unavailable'), ('available', 'Available'), ('adopted', 'Adopted')], default='unavailable', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
